export const hiraganaSet = [
  { character: 'あ', romanization: 'a' },
  { character: 'い', romanization: 'i' },
  { character: 'う', romanization: 'u' },
  { character: 'え', romanization: 'e' },
  { character: 'お', romanization: 'o' },
  { character: 'か', romanization: 'ka' },
  { character: 'き', romanization: 'ki' },
  { character: 'く', romanization: 'ku' },
  { character: 'け', romanization: 'ke' },
  { character: 'こ', romanization: 'ko' },
  { character: 'さ', romanization: 'sa' },
  { character: 'し', romanization: 'shi' },
  { character: 'す', romanization: 'su' },
  { character: 'せ', romanization: 'se' },
  { character: 'そ', romanization: 'so' },
  { character: 'た', romanization: 'ta' },
  { character: 'ち', romanization: 'chi' },
  { character: 'つ', romanization: 'tsu' },
  { character: 'て', romanization: 'te' },
  { character: 'と', romanization: 'to' },
  { character: 'な', romanization: 'na' },
  { character: 'に', romanization: 'ni' },
  { character: 'ぬ', romanization: 'nu' },
  { character: 'ね', romanization: 'ne' },
  { character: 'の', romanization: 'no' },
  { character: 'は', romanization: 'ha' },
  { character: 'ひ', romanization: 'hi' },
  { character: 'ふ', romanization: 'fu' },
  { character: 'へ', romanization: 'he' },
  { character: 'ほ', romanization: 'ho' },
  { character: 'ま', romanization: 'ma' },
  { character: 'み', romanization: 'mi' },
  { character: 'む', romanization: 'mu' },
  { character: 'め', romanization: 'me' },
  { character: 'も', romanization: 'mo' },
  { character: 'や', romanization: 'ya' },
  { character: 'ゆ', romanization: 'yu' },
  { character: 'よ', romanization: 'yo' },
  { character: 'ら', romanization: 'ra' },
  { character: 'り', romanization: 'ri' },
  { character: 'る', romanization: 'ru' },
  { character: 'れ', romanization: 're' },
  { character: 'ろ', romanization: 'ro' },
  { character: 'わ', romanization: 'wa' },
  { character: 'を', romanization: 'wo' },
  { character: 'ん', romanization: 'n' },
]

export const sentences = [
  {
    japanese: 'この商品は免税ですか？',
    korean: '이 상품은 면세입니까?',
    topic: '쇼핑',
    relatedWords: ['免税(めんぜい) - 면세', '商品(しょうひん) - 상품'],
    pronunciation: '코노 쇼히와 멘제이데스까?',
  },
  {
    japanese: 'この商品は返品できますか？',
    korean: '이 상품은 반품할 수 있습니까?',
    topic: '쇼핑',
    relatedWords: ['返品(へんぴん) - 반품', '商品(しょうひん) - 상품'],
    pronunciation: '코노 쇼히와 헨핀데키마스까?',
  },
  {
    japanese: 'この商品はサイズが合いません。交換できますか？',
    korean: '이 상품은 사이즈가 맞지 않습니다. 교환할 수 있습니까?',
    topic: '쇼핑',
    relatedWords: ['サイズ(サイズ) - 사이즈', '交換(こうかん) - 교환', '商品(しょうひん) - 상품'],
    pronunciation: '코노 쇼히와 사이즈가 아이마센. 코우칸데키마스까?',
  },
  {
    japanese: 'この商品はいつ届きますか？',
    korean: '이 상품은 언제 도착합니까?',
    topic: '쇼핑',
    relatedWords: ['商品(しょうひん) - 상품', '届く(とどく) - 도착하다'],
    pronunciation: '코노 쇼히와 언제 토도키마스까?',
  },
  {
    japanese: 'この商品はオンラインで購入できますか？',
    korean: '이 상품은 온라인에서 구매할 수 있습니까?',
    topic: '쇼핑',
    relatedWords: [
      'オンライン(オンライン) - 온라인',
      '購入(こうにゅう) - 구매',
      '商品(しょうひん) - 상품',
    ],
    pronunciation: '코노 쇼히와 온라인데 고우뉴데키마스까?',
  },
  {
    japanese: 'この商品は割引がありますか？',
    korean: '이 상품은 할인이 있습니까?',
    topic: '쇼핑',
    relatedWords: ['割引(わりびき) - 할인', '商品(しょうひん) - 상품'],
    pronunciation: '코노 쇼히와 와리비키가 아리마스까?',
  },
  {
    japanese: 'この商品はプレゼント用に包装できますか？',
    korean: '이 상품은 선물용으로 포장할 수 있습니까?',
    topic: '쇼핑',
    relatedWords: [
      'プレゼント(プレゼント) - 선물',
      '包装(ほうそう) - 포장',
      '商品(しょうひん) - 상품',
    ],
    pronunciation: '코노 쇼히와 프레젠토니 호소오데키마스까?',
  },
  {
    japanese: 'この商品はクレジットカードで支払えますか？',
    korean: '이 상품은 신용카드로 결제할 수 있습니까?',
    topic: '쇼핑',
    relatedWords: [
      'クレジットカード(クレジットカード) - 신용카드',
      '支払う(しはらう) - 결제하다',
      '商品(しょうひん) - 상품',
    ],
    pronunciation: '코노 쇼히와 쿠레딧카드데 시하라에마스까?',
  },
  {
    japanese: '今日はいい天気ですね。',
    korean: '오늘은 날씨가 참 좋ですね.',
    topic: '기타',
    relatedWords: ['天気(てんき) - 날씨'],
    pronunciation: '쿄와와 이이 텐키데스네.',
  },
  {
    japanese: '日本食が好きですか？',
    korean: '일본 음식을 좋아하시나요?',
    topic: '기타',
    relatedWords: ['日本食(にほんしょく) - 일본 음식'],
    pronunciation: '니혼쇼쿠가 스키데스까?',
  },
  {
    japanese: 'また日本に来てくださいね。',
    korean: '또 일본에 오세요.',
    topic: '기타',
    relatedWords: ['また(また) - 또'],
    pronunciation: '마타 니혼니 키테 쿠다사이.',
  },
  {
    japanese: 'さようなら。',
    korean: '안녕히 가세요.',
    topic: '기타',
    relatedWords: [],
    pronunciation: '사요나라.',
  },
  {
    japanese: '日本円に両替したいです。',
    korean: '일원으로 환전하고 싶습니다.',
    topic: '기타',
    relatedWords: ['日本円(にほんえん) - 일원', '両替(りょうがえ) - 환전', 'したい - 하고싶다'],
    pronunciation: '니혼엔니 료가에시타이데스.',
  },
  {
    japanese: 'SIMカードはどこで買えますか？',
    korean: 'SIM카드는 어디에서 살 수 있습니까?',
    topic: '기타',
    relatedWords: ['SIMカード(SIMカード) - SIM카드'],
    pronunciation: '시무카드와 도코데 카에마스까?',
  },
  {
    japanese: '病気になりました。病院を教えてください。',
    korean: '아프게 되었습니다. 병원을 알려주세요.',
    topic: '기타',
    relatedWords: [
      '病気(びょうき) - 병',
      '病院(びょういん) - 병원',
      'おしえる(教える) - 가르치다',
      'くださる(下さる) - 주시다',
    ],
    pronunciation: '병키니 나리마시타. 병원오 오시에테 쿠다사이.',
  },
  {
    japanese: '警察を呼んでください。',
    korean: '경찰을 불러주세요.',
    topic: '기타',
    relatedWords: ['警察(けいさつ) - 경찰'],
    pronunciation: '게이사츠오 요んで 쿠다사이.',
  },
  {
    japanese: '助けてください。',
    korean: '도와주세요.',
    topic: '기타',
    relatedWords: [],
    pronunciation: '타스케테 쿠다사이.',
  },
  {
    japanese: 'このホテルに泊まりたいです。',
    korean: '이 호텔에 묵고 싶습니다.',
    topic: '숙박',
    relatedWords: ['ホテル(ホテル) - 호텔'],
    pronunciation: '코노 호테루니 토마리타이데스.',
  },
  {
    japanese: 'チェックインしたいです。',
    korean: '체크인하고 싶습니다.',
    topic: '숙박',
    relatedWords: ['チェックイン(チェックイン) - 체크인'],
    pronunciation: '체키인시타이데스.',
  },
  {
    japanese: 'チェックアウトしたいです。',
    korean: '체크아웃하고 싶습니다.',
    topic: '숙박',
    relatedWords: ['チェックアウト(チェックアウト) - 체크아웃'],
    pronunciation: '체키아웃시타이데す.',
  },
  {
    japanese: '荷物を預けたいです。',
    korean: '짐을 맡기고 싶습니다.',
    topic: '숙박',
    relatedWords: ['荷物(にもの) - 짐', 'あずける(預ける) - 맡기다'],
    pronunciation: '니모쯔오 아즈케타이데스.',
  },
  {
    japanese: '部屋にWi-Fiはありますか？',
    korean: '방에 와이파이는 있습니까?',
    topic: '숙박',
    relatedWords: ['部屋(へや) - 방', 'Wi-Fi(ワイファイ) - 와이파이'],
    pronunciation: '헤야니 와이파이와 아리마스까?',
  },
  {
    japanese: '朝食は付いていますか？',
    korean: '아침식사는 포함되어 있습니까?',
    topic: '숙박',
    relatedWords: ['朝食(ちょうしょく) - 아침식사'],
    pronunciation: '초쇼쿠와 츠이테 이마스까?',
  },
  {
    japanese: '温泉はありますか？',
    korean: '온천은 있습니까?',
    topic: '숙박',
    relatedWords: ['温泉(おんせん) - 온천'],
    pronunciation: '온센와 아리마스까?',
  },
  {
    japanese: '観光地はどこですか？',
    korean: '관광지는 어디입니까?',
    topic: '여행',
    relatedWords: ['観光地(かんこうち) - 관광지'],
    pronunciation: '칸코오치와 도코데스까?',
  },
  {
    japanese: 'おすすめのお店はどこですか？',
    korean: '추천 가게는 어디입니까?',
    topic: '여행',
    relatedWords: ['おすすめ(おすすめ) - 추천', 'お店(おみせ) - 가게'],
    pronunciation: '오스스메노 오미세와 도코데스까?',
  },
  {
    japanese: 'イベントはありますか？',
    korean: '이벤트는 있습니까?',
    topic: '여행',
    relatedWords: ['イベント(イベント) - 이벤트'],
    pronunciation: '이벤트와 아리마스까?',
  },
  {
    japanese: '伝統工芸品はどこで買えますか？',
    korean: '전통 공예품은 어디에서 살 수 있습니까?',
    topic: '여행',
    relatedWords: ['伝統工芸品(でんとうこうげいひん) - 전통 공예품'],
    pronunciation: '덴토우코우게이히와 도코데 카에마스까?',
  },
  {
    japanese: 'この服はいくらですか？',
    korean: '이 옷은 얼마입니까?',
    topic: '쇼핑',
    relatedWords: ['服(ふく) - 옷', 'いくら(いくら) - 얼마'],
    pronunciation: '코노 후쿠와 이쿠라데스까?',
  },
  {
    japanese: '試着できますか？',
    korean: '입어볼 수 있습니까?',
    topic: '쇼핑',
    relatedWords: ['試着(しちやく) - 입어보기'],
    pronunciation: '시차쿠데키마스까?',
  },
  {
    japanese: '値引きできますか？',
    korean: '할인해주세요.',
    topic: '쇼핑',
    relatedWords: ['値引き(ねびき) - 할인'],
    pronunciation: '네비키데키마스까?',
  },
  {
    japanese: '包装してください。',
    korean: '포장해주세요.',
    topic: '쇼핑',
    relatedWords: ['包装(ほうそう) - 포장'],
    pronunciation: '호소오시테 쿠다사이.',
  },
  {
    japanese: 'クレジットカードは使えますか？',
    korean: '신용카드는 사용할 수 있습니까?',
    topic: '쇼핑',
    relatedWords: ['クレジットカード(クレジットカード) - 신용카드'],
    pronunciation: '쿠레디트카드와 쓰케마스까?',
  },
  {
    japanese: '免税の手続きはできますか？',
    korean: '면세 절차는 할 수 있습니까?',
    topic: '쇼핑',
    relatedWords: ['免税(めんぜい) - 면세', '手続き(てつづき) - 절차'],
    pronunciation: '멘제이노 테츠즈키와 데키마스까?',
  },
  {
    japanese: 'この電車はいつ来ますか？',
    korean: '이 전차는 언제 옵니까?',
    topic: '교통',
    relatedWords: ['電車(でんしゃ) - 전차', 'いつ(いつ) - 언제'],
    pronunciation: '코노 덴샤와 이츠키마스까?',
  },
  {
    japanese: 'このバスはどこに行きますか？',
    korean: '이 버스는 어디로 가나요?',
    topic: '교통',
    relatedWords: ['バス(バス) - 버스', 'どこ(どこ) - 어디'],
    pronunciation: '코노 바스와 도코니 이키마스까?',
  },
  {
    japanese: 'このタクシーは空いていますか？',
    korean: '이 택시는 빈칸입니까?',
    topic: '교통',
    relatedWords: ['タクシー(タクシー) - 택시', '空いている(すいている) - 빈'],
    pronunciation: '코노 택시와 스이테 이마스까?',
  },
  {
    japanese: 'この切符はいくらですか？',
    korean: '이 표는 얼마입니까?',
    topic: '교통',
    relatedWords: ['切符(きっぷ) - 표'],
    pronunciation: '코노 키뿌와 이쿠라데스까?',
  },
  {
    japanese: '降りたいのですが、どこで降りたらいいですか？',
    korean: '내리고 싶은데, 어디에서 내리면 좋습니까?',
    topic: '교통',
    relatedWords: ['おりる(降りる) - (탈것·역 등에서) 내리다. (↔乗る)'],
    pronunciation: '오리타이노데스가, 도코데 오리타라 이이데스까?',
  },
  {
    japanese: '日本語のメニューをいただけますか？',
    korean: '일본어 메뉴를 받을 수 있습니까?',
    topic: '음식',
    relatedWords: ['日本語(にほんご) - 일본어', 'メニュー(メニュー) - 메뉴'],
    pronunciation: '니혼고노 메뉴오 이타다케마스까?',
  },
  {
    japanese: 'アレルギーがあります。何が入っていますか？',
    korean: '알레르기가 있습니다. 무엇이 들어 있습니까?',
    topic: '음식',
    relatedWords: ['アレルギー(アレルギー) - 알레르기', '何(なに) - 무엇'],
    pronunciation: '아레르기가 아리마스. 나니가 하이테 이마스까?',
  },
  {
    japanese: 'この料理は辛いですか？',
    korean: '이 요리는 매운가요?',
    topic: '음식',
    relatedWords: ['料理(りょうり) - 요리', '辛い(からい) - 매운'],
    pronunciation: '코노 료리와 가라이데스까?',
  },
  {
    japanese: 'おすすめは何ですか？',
    korean: '추천은 무엇입니까?',
    topic: '음식',
    relatedWords: ['おすすめ(おすすめ) - 추천', '何ですか(なんですか?) - 무엇입니까?'],
    pronunciation: '오스스메와 나니데스까?',
  },
  {
    japanese: 'お会計をお願いします',
    korean: '계산 부탁합니다',
    topic: '음식',
    relatedWords: ['おかいけい(お会計) - 계산'],
    pronunciation: '오카이계이 오네가이시마스',
  },
  {
    japanese: 'トイレはどこですか？',
    korean: '화장실은 어디입니까?',
    topic: '기타',
    relatedWords: ['トイレ(トイレ) - 화장실'],
    pronunciation: '토이레와 도코데스까?',
  },
  {
    japanese: 'Wi-Fiは使えますか？',
    korean: '와이파이는 사용할 수 있습니까?',
    topic: '기타',
    relatedWords: ['Wi-Fi(ワイファイ) - 와이파이'],
    pronunciation: '와이파이와 쓰케마스까?',
  },
  {
    japanese: 'トラブルが発生しました。助けてください。',
    korean: '문제가 발생했습니다. 도와주세요.',
    topic: '기타',
    relatedWords: ['トラブル(トラブル) - 문제', '助けてください(たすけてください) - 도와주세요'],
    pronunciation: '토루부루가 하쿠세이시마시타. 타스케테 쿠다사이.',
  },
  {
    japanese: '日本語がわからないのですが、英語で話せますか？',
    korean: '일본어를 모르는데, 영어로 말할 수 있습니까?',
    topic: '기타',
    relatedWords: ['日本語(にほんご) - 일본어', '英語(えいご) - 영어'],
    pronunciation: '니혼고가 와카리마셍데스가, 영어데 하나세루카?',
  },
  {
    japanese: 'この地図を貸してください。',
    korean: '이 지도를 빌려주세요.',
    topic: '기타',
    relatedWords: ['地図(ちず) - 지도'],
    pronunciation: '코노 지마오 카시테 쿠다사이.',
  },
  {
    japanese: 'この場所はどこですか？',
    korean: '이 장소는 어디입니까?',
    topic: '기타',
    relatedWords: ['場所(ばしょ) - 장소'],
    pronunciation: '코노 바쇼와 도코데스까?',
  },
  {
    japanese: '日本の歴史について学び(まなび)たい',
    korean: '일본의 역사에 대해 배우고 싶습니다',
    topic: '여행',
    relatedWords: ['歴史(れきし) - 역사', '学び(まなび)たい - 배우고 싶다'],
    pronunciation: '니혼노 레키시니 쓰이테 마나비타이',
  },
  {
    japanese: '日本の文化について学び(まなび)たい',
    korean: '일본의 문화에 대해 배우고 싶습니다',
    topic: '여행',
    relatedWords: ['文化(ぶんか) - 문화', '学び(まなび)たい - 배우고 싶다'],
    pronunciation: '니혼노 분카니 쓰이테 마나비타이',
  },
  {
    japanese: '日本の友達が欲しいです',
    korean: '일본의 친구가 필요합니다',
    topic: '여행',
    relatedWords: ['友達(ともだち) - 친구', 'ほしい(欲しい) - 바라다, 요망하다'],
    pronunciation: '니혼노 토모다치가 호시이데스',
  },
  {
    japanese: '日本語を勉強しています',
    korean: '일본어를 공부하고 있습니다',
    topic: '여행',
    relatedWords: ['日本語(にほんご) - 일본어'],
    pronunciation: '니혼고오 벤쿄오시테 이마스',
  },
  {
    japanese: '日本が好きです',
    korean: '일본을 좋아합니다',
    topic: '여행',
    relatedWords: ['日本(にほん) - 일본'],
    pronunciation: '니혼고 스키데스',
  },
  {
    japanese: 'また日本に来(きた)たいです',
    korean: '다시 일본에 오고 싶습니다',
    topic: '여행',
    relatedWords: ['また(また) - 다시', '日本(にほん) - 일본'],
    pronunciation: '마타 니혼니 키타이데스',
  },
  {
    japanese: 'ありがとうございました',
    korean: '감사합니다',
    topic: '기타',
    relatedWords: [],
    pronunciation: '아리가토 고자이마스',
  },
  {
    japanese: 'さようなら',
    korean: '안녕히 가세요',
    topic: '기타',
    relatedWords: [],
    pronunciation: '사요나라',
  },
  {
    japanese: '良い旅を',
    korean: '좋은 여행 되세요',
    topic: '기타',
    relatedWords: [],
    pronunciation: '요이 타비오',
  },
  {
    japanese: '電車でどこに行けばいいですか？',
    korean: '기차로 어디로 가야 하나요?',
    topic: '교통',
    relatedWords: ['電車(でんしゃ) - 기차', 'どこ(どこ) - 어디'],
    pronunciation: '덴샤데 도코니 이케바 이이데스까?',
  },
  {
    japanese: 'バスでどこに行けばいいですか？',
    korean: '버스로 어디로 가야 하나요?',
    topic: '교통',
    relatedWords: ['バス(バス) - 버스', 'どこ(どこ) - 어디'],
    pronunciation: '바스데 도코니 이케바 이이데스까?',
  },
  {
    japanese: 'タクシーでどこに行けばいいですか？',
    korean: '택시로 어디로 가야 하나요?',
    topic: '교통',
    relatedWords: ['タクシー(택시) - 택시', 'どこ(どこ) - 어디'],
    pronunciation: '택시데 도코니 이케바 이이데스까?',
  },
  {
    japanese: '駅はどこですか？',
    korean: '역은 어디입니까?',
    topic: '교통',
    relatedWords: ['駅(えき) - 역'],
    pronunciation: '에키와 도코데스까?',
  },
  {
    japanese: '助けてください',
    korean: '도와주세요',
    topic: '기타',
    relatedWords: [],
    pronunciation: '타스케테 쿠다사이',
  },
  {
    japanese: '警察を呼んでください',
    korean: '경찰을 불러주세요',
    topic: '기타',
    relatedWords: ['警察(けいさつ) - 경찰'],
    pronunciation: '게이사츠오 요んで 쿠다사이',
  },
  {
    japanese: '病院を教えてください',
    korean: '병원을 알려주세요',
    topic: '기타',
    relatedWords: ['病院(びょういん) - 병원'],
    pronunciation: '비요엔오 오시에테 쿠다사이',
  },
  {
    japanese: '日本の伝統工芸品を見たい',
    korean: '일본의 전통 공예품을 보고 싶습니다',
    topic: '여행',
    relatedWords: ['伝統工芸品(でんとうこうげいひん) - 전통 공예품'],
    pronunciation: '니혼노 덴토우코우게이부츠오 미타이',
  },
  {
    japanese: '日本の伝統舞踊を見たい',
    korean: '일본의 전통 무용을 보고 싶습니다',
    topic: '여행',
    relatedWords: ['伝統舞踊(でんとうぶよう) - 전통 무용'],
    pronunciation: '니혼노 덴토우부요오 미타이',
  },
  {
    japanese: '日本の伝統料理を食べたい',
    korean: '일본의 전통 요리를 먹고 싶습니다',
    topic: '여행',
    relatedWords: ['伝統料理(でんとうりょうり) - 전통 요리'],
    pronunciation: '니혼노 덴토우료리오 타베타이',
  },
  {
    japanese: '日本の祭りに参加したいです',
    korean: '일본의 축제에 참여하고 싶습니다',
    topic: '여행',
    relatedWords: ['祭り(まつり) - 축제'],
    pronunciation: '니혼노 오마츠리니 산카시타이데스',
  },
  {
    japanese: '日本の自然を満喫したい',
    korean: '일본의 자연을 만끽하고 싶습니다',
    topic: '여행',
    relatedWords: ['自然(しぜん) - 자연'],
    pronunciation: '니혼노 시젠오 만키츠시타이',
  },
  {
    japanese: '空港から市内まではどうやって行けますか？',
    korean: '공항에서 시내로 어떻게 가나요?',
    topic: '교통',
    relatedWords: [
      '空港(くうこう) - 공항',
      '市内(しない) - 시내',
      'どうやって行けますか？ - 어떻게 갈 수 있나요?',
    ],
    pronunciation: '쿠우코오카라 시나이마데와 도오 얏테이케마스카?',
  },
  {
    japanese: '電車の切符を教えてください',
    korean: '기차표를 알려주세요',
    topic: '교통',
    relatedWords: ['電車(でんしゃ) - 기차', '切符(きっぷ) - 표'],
    pronunciation: '덴샤노 키뿌오 오시에테 쿠다사이',
  },
  {
    japanese: 'ホテルの場所を教えてください',
    korean: '호텔의 위치를 알려주세요',
    topic: '숙박',
    relatedWords: ['ホテル(ホテル) - 호텔', '場所(ばしょ) - 위치'],
    pronunciation: '호텔노 바쇼오 오시에테 쿠다사이',
  },
  {
    japanese: 'レストランを探しています',
    korean: '식당을 찾고 있습니다',
    topic: '쇼핑',
    relatedWords: ['レストラン(レストラン) - 식당', '探す(さがす) - 찾다'],
    pronunciation: '레스토랑오 사가시테 이마스',
  },
  {
    japanese: '道順を教えてください',
    korean: '길 안내를 부탁드립니다',
    topic: '교통',
    relatedWords: ['道順(みちすじ) - 길 안내'],
    pronunciation: '미치스루오 오시에테 쿠다사이',
  },
  {
    japanese: '日本語がわからないのですが、英語で話せますか？',
    korean: '일본어를 모르는데, 영어로 말할 수 있습니까?',
    topic: '기타',
    relatedWords: ['日本語(にほんご) - 일본어', '英語(えいご) - 영어'],
    pronunciation: '니혼고가 와카리마셍데스가, 영어데 하나세루카?',
  },
  {
    japanese: 'この地図を貸してください',
    korean: '이 지도를 빌려주세요',
    topic: '기타',
    relatedWords: ['地図(ちず) - 지도'],
    pronunciation: '코노 지마오 카시테 쿠다사이',
  },
  {
    japanese: 'この場所はどこですか？',
    korean: '이 장소는 어디입니까?',
    topic: '기타',
    relatedWords: ['場所(ばしょ) - 장소'],
    pronunciation: '코노 바쇼와 도코데스까?',
  },
  {
    japanese: 'このお店は人気がありますか？',
    korean: '이 가게는 인기가 있으십니까?',
    topic: '음식',
    relatedWords: ['人気(にんき) - 인기', 'お店(おみせ) - 가게'],
    pronunciation: '코노 오미세와 닌키가 아리마스까?',
  },
  {
    japanese: 'この料理は辛いですか？',
    korean: '이 요리는 매운가요?',
    topic: '음식',
    relatedWords: ['料理(りょうり) - 요리', '辛い(からい) - 매운'],
    pronunciation: '코노 료리와 가라이데스까?',
  },
  {
    japanese: 'この料理はベジタリアン対応ですか？',
    korean: '이 요리는 채식주의자 대응이ですか?',
    topic: '음식',
    relatedWords: ['ベジタリアン(ベジタリアン) - 채식주의자', '対応(たいおう) - 대응'],
    pronunciation: '코노 료리와 베지타리아엔 타이오우데스까?',
  },
  {
    japanese: 'この料理はアレルギー対応ですか？',
    korean: '이 요리는 알레르기 대응이ですか?',
    topic: '음식',
    relatedWords: ['アレルギー(アレルギー) - 알레르기', '対応(たいおう) - 대응'],
    pronunciation: '코노 료리와 아레르기 타이오우데스까?',
  },
  {
    japanese: 'この料理はテイクアウトできますか？',
    korean: '이 요리는 테이크아웃 할 수 있습니까?',
    topic: '음식',
    relatedWords: ['テイクアウト(テイクアウト) - 테이크아웃'],
    pronunciation: '코노 료리와 테이쿠아우토데키마스까?',
  },
  {
    japanese: 'この料理は何がおすすめですか？',
    korean: '이 요리 중에는 무엇이 추천이ですか?',
    topic: '음식',
    relatedWords: ['おすすめ(おすすめ) - 추천', '料理(りょうり) - 요리'],
    pronunciation: '코노 료리 중에는 나니가 오스스메데스까?',
  },
  {
    japanese: 'この料理はお酒に合いますか？',
    korean: '이 요리는 술에 合う가요?',
    topic: '음식',
    relatedWords: ['お酒(おさけ) - 술', '合う(あう) - 合う'],
    pronunciation: '코노 료리와 오사케니 아우데스까?',
  },
  {
    japanese: 'この料理はどの席に座ると景色がいいですか？',
    korean: '이 요리는 어떤 자리에 앉으면 전망이 좋습니까?',
    topic: '음식',
    relatedWords: ['景色(けしき) - 전망', '席(せき) - 자리'],
    pronunciation: '코노 료리와 도노 세키니 아즈와 케시키가 이이데스까?',
  },
  {
    japanese: 'このお店は予約が必要ですか？',
    korean: '이 가게는 예약이 필요합니까?',
    topic: '음식',
    relatedWords: ['予約(よやく) - 예약', '必要(ひつよう) - 필요'],
    pronunciation: '코노 오미세와 요약이 히츠요우데스까?',
  },
  {
    japanese: 'このお店はクレジットカードで支払えますか？',
    korean: '이 가게는 신용카드로 결제할 수 있습니까?',
    topic: '음식',
    relatedWords: ['クレジットカード(クレジットカード) - 신용카드', '支払う(しはらう) - 결제하다'],
    pronunciation: '코노 오미세와 쿠레딧카드데 시하라에마스까?',
  },
  {
    japanese: '日本語の電子書籍はありますか？',
    korean: '일본어 전자책이 있습니까?',
    topic: '교육/학습',
    relatedWords: ['日本語(にほんご) - 일본어', '電子書籍(でんししょせき) - 전자책'],
    pronunciation: '니혼고노 덴시쇼세키가 아리마스까?',
  },
  {
    japanese: '近くでおいしいラーメン屋はありますか？',
    korean: '근처에 맛있는 라멘집이 있습니까?',
    topic: '식사/음식',
    relatedWords: ['近く(ちかく) - 근처', 'おいしい - 맛있는', 'ラーメン屋(ラーメンや) - 라멘집'],
    pronunciation: '치카쿠데 오이시이 라멘야가 아리마스까?',
  },
  {
    japanese: '日本でおすすめの観光地はどこですか？',
    korean: '일본에서 추천하는 관광지는 어디입니까?',
    topic: '여가/활동',
    relatedWords: ['日本(にほん) - 일본', 'おすすめ - 추천', '観光地(かんこうち) - 관광지'],
    pronunciation: '니혼데 오스스메노 칸코우치와 도코데스까?',
  },
  {
    japanese: 'この博物館の開館時間はいつですか？',
    korean: '이 박물관의 개관 시간은 언제입니까?',
    topic: '여가/활동',
    relatedWords: [
      '博物館(はくぶつかん) - 박물관',
      '開館時間(かいかんじかん) - 개관 시간',
      'はいつですか - 언제 입니까',
    ],
    pronunciation: '코노 하쿠부츠칸노 카이칸지칸와 난데스까?',
  },
  {
    japanese: '日本で一番有名な寺はどこですか？',
    korean: '일본에서 가장 유명한 사찰은 어디입니까?',
    topic: '문화/역사',
    relatedWords: [
      '日本(にほん) - 일본',
      '一番(いちばん) - 가장',
      '有名(ゆうめい) - 유명',
      '寺(てら) - 사찰',
    ],
    pronunciation: '니혼데 이치반 유우메이나 테라와 도코데스까?',
  },
  {
    japanese: '日本語で対応できる観光ガイドはありますか？',
    korean: '일본어로 대응 가능한 관광 가이드가 있습니까?',
    topic: '여가/활동',
    relatedWords: [
      '日本語(にほんご) - 일본어',
      '対応(たいおう) - 대응',
      '観光ガイド - 관광 가이드',
    ],
    pronunciation: '니혼고데 타이오우 데키루 칸코우 가이도가 아리마스까?',
  },
  {
    japanese: '日本語の新聞はありますか？',
    korean: '일본어 신문이 있습니까?',
    topic: '숙박/일상',
    relatedWords: ['日本語(にほんご) - 일본어', '新聞(しんぶん) - 신문'],
    pronunciation: '니혼고노 신분와 아리마스까?',
  },
  {
    japanese: '最寄りの地下鉄の駅はどこですか？',
    korean: '가장 가까운 지하철 역은 어디입니까?',
    topic: '교통',
    relatedWords: ['最寄り(もより) - 가장 가까운', '地下鉄(ちかてつ) - 지하철', '駅(えき) - 역'],
    pronunciation: '모요리노 치카테츠노 에키와 도코데스까?',
  },
  {
    japanese: '近くの観光スポットはどこですか？',
    korean: '근처의 관광 명소는 어디입니까?',
    topic: '여가/활동',
    relatedWords: ['近く(ちかく) - 근처', '観光(かんこう) - 관광', 'スポット - 명소'],
    pronunciation: '치카쿠노 칸코우 스포츠와 도코데스까?',
  },
  {
    japanese: 'このレストランの特別な料理は何ですか？',
    korean: '이 레스토랑의 특별한 요리는 무엇입니까?',
    topic: '식사/음식',
    relatedWords: ['レストラン - 레스토랑', '特別(とくべつ) - 특별', '料理(りょうり) - 요리'],
    pronunciation: '코노 레스토랑노 토쿠베츠나 료우리와 난데스까?',
  },
  {
    japanese: '乗り遅れそうなのですが、どうすればいいですか？',
    korean: '탈 시간이 지났는데, 어떻게 하면 좋습니까?',
    topic: '교통',
    relatedWords: ['乗り遅れ(のりおくれ) - 늦게 타다', 'どうすれば - 어떻게 하면'],
    pronunciation: '노리오치리소우나노데스가, 도우스레바 ii데스까?',
  },
  {
    japanese: '電車はいつ来ますか？',
    korean: '기차는 언제 옵니까?',
    topic: '교통',
    relatedWords: ['電車(でんしゃ) - 기차', 'いつ - 언제'],
    pronunciation: '덴샤와 이츠키마스까?',
  },
  // 기타
  {
    japanese: '日本語で書いてください',
    korean: '일본어로 써주세요.',
    topic: '기타',
    relatedWords: ['日本語(にほんご) - 일본어', '書いて(かいて) - 쓰다'],
    pronunciation: '니혼고데 카이테 쿠다사이',
  },
  {
    japanese: '翻訳機はありますか？',
    korean: '번역기가 있습니까?',
    topic: '기타',
    relatedWords: ['翻訳機(ほんやくき) - 번역기'],
    pronunciation: '혼야쿠키가 아리마스까?',
  },
  {
    japanese: '日本の四季は美しいです',
    korean: '일본의 사계절은 아름답습니다.',
    topic: '여행',
    relatedWords: ['四季(しき) - 사계절', '美しい(うつくしい) - 아름답다'],
    pronunciation: '니혼노 시키와 우치데스',
  },
  {
    japanese: '日本の伝統芸能は素晴らしいです',
    korean: '일본의 전통 예능은 정말 멋집니다.',
    topic: '여행',
    relatedWords: ['伝統芸能(でんとうげいのう) - 전통 예능', '素晴らしい(すばらしい) - 멋지다'],
    pronunciation: '니혼노 덴토우게이노우와 스바라시이데스',
  },
  // 쇼핑
  {
    japanese: 'おすすめのお店はありますか？',
    korean: '추천하는 가게가 있습니까?',
    topic: '쇼핑',
    relatedWords: ['おすすめ(おすすめ) - 추천', 'お店(おみせ) - 가게'],
    pronunciation: '오소스메노 오미세가 아리마스까',
  },
  {
    japanese: 'セールはありますか？',
    korean: '세일이 있습니까?',
    topic: '쇼핑',
    relatedWords: ['セール(セール) - 세일'],
    pronunciation: '세일와 아리마스까',
  },
  // 숙박
  {
    japanese: '日本語のチャンネルはありますか？',
    korean: '일본어 채널이 있습니까?',
    topic: '숙박',
    relatedWords: [
      '日本語(にほんご) - 일본어',
      'チャンネル(チャンネル) - 채널',
      'ありますか？ - 있습니까?',
    ],
    pronunciation: '니혼고노 챤네루가 아리마스까',
  },
]
